/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject3;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ClassNotFoundException {
        NewJFrame nj=new NewJFrame();
        nj.setVisible(true);
           

}}
